os:
    - linux
# Ubuntu 14.04 to use newer Boost version
dist: trusty
sudo: required
compiler:
    - gcc
addons:
  apt:
    packages:
      - libboost-all-dev
script: make && make test && make clean
