# Ubuntu 14.04 to use newer Boost version
os:
  - linux
dist: trusty
sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
      - libboost-all-dev
      - httpie
      - lcov
      - telnet

script: make && make test && make clean
