# Ubuntu 14.04 to use newer Boost version
os:
  - linux
dist: trusty
sudo: true

compiler:
  - gcc

addons:
  apt:
    packages:
      - libboost-all-dev
      - httpie
      - lcov
      - telnet

install:
    - sudo apt-get install -y python-software-properties
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y ppa:jonathonf/python-3.6
    - sudo apt-get install -y python3.6

script: make && make test && make clean
