FROM busybox:ubuntu-14.04

# Avoid running as root within the container
RUN groupadd -r user && useradd -r -g user user
USER user

# Disable setuid rights to prevent privilege escalation
RUN find / -perm +6000 -type f -exec chmod a-s {} \; \ || true

WORKDIR /opt/lightning-webserver
# Copy files from deploy/ directory into image's working directory
COPY . /opt/lightning-webserver

EXPOSE 8080:8080

CMD ["./lightning", "simple_config"]
